HOV-14 | Checkbox Component
antstackio/hover-design pull request #100
Opened 2022-09-13 18:51 UTC by Raalzz

## Description

Adds Checkbox Component

## Motivation and Context

## How Has This Been Tested?

Tested in local and Docs

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2022-09-15 13:02 UTC, pruthvi2103 commented
is this ready for review @Raalzz ?

2022-09-15 13:03 UTC, Raalzz commented
Yes

2022-09-16 06:10 UTC, pruthvi2103 requested changes
Added comments

2022-09-16 06:10 UTC, pruthvi2103 commented on lib/src/components/_internal/Icons/SvgCheck.tsx
> +export { SvgCheck };
Use the `Icon` Component to wrap this

2022-09-16 06:10 UTC, pruthvi2103 commented on lib/src/components/_internal/Icons/SvgDash.tsx
> +    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 6">
use `Icon` instead of `svg`

2022-09-16 07:35 UTC, Raalzz commented on lib/src/components/_internal/Icons/SvgDash.tsx
> +    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 6">
Done

2022-09-16 07:37 UTC, pruthvi2103 approved these changes
LGTM

2022-09-16 07:37 UTC, merged