HOV-31 | Adds Alert component
antstackio/hover-design pull request #124
Opened 2022-09-21 11:50 UTC by saurabhsutar192

Adds Alert Component

## Description
A customizable Alert component with type, variant support etc

## Motivation and Context
Alert Component Needed!

## How Has This Been Tested?
Local Build Success and manual testing

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-09-28 07:37 UTC, pruthvi2103 requested changes
just one small question

2022-09-28 07:37 UTC, pruthvi2103 commented on lib/src/components/Button/Button.stories.tsx
> -  ...nativeProps
why changes here?

2022-09-28 12:15 UTC, saurabhsutar192 commented on lib/src/components/Button/Button.stories.tsx
> -  ...nativeProps
slacked you the details

2022-09-29 01:31 UTC, pruthvi2103 approved these changes
LGTM

2022-09-29 01:32 UTC, pruthvi2103 commented
@saurabhsutar192 can you please resolve the code smells pointed out by sonar cloud

2022-09-30 06:50 UTC, merged