HOV-104 | Create Util function to handle custom values
antstackio/hover-design pull request #169
Opened 2023-01-31 07:40 UTC by Raalzz

…mponent

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-02-01 23:16 UTC, pruthvi2103 requested changes
Just remove that comment

2023-02-01 23:16 UTC, pruthvi2103 commented on packages/lib/src/components/Radio/radio.styles.css.ts
> +//Radio Default Values
remove comment

2023-02-02 07:51 UTC, Raalzz commented on packages/lib/src/components/Radio/radio.styles.css.ts
> +//Radio Default Values
done

2023-02-02 21:19 UTC, pruthvi2103 approved these changes
LGTM

2023-02-02 21:19 UTC, merged